version: '3.9'

services:

  web:
    image: veterans-registration
    restart: unless-stopped
    build: .docker
    volumes:
      - ./:/var/www/html
      - ./.docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 80:80
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    links:
      - database

  cron_server:
    image: cron_server
    restart: unless-stopped
    build: .docker/cron
    volumes:
      - ./:/var/www/html
    links:
      - database

  database:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./.docker/database:/docker-entrypoint-initdb.d:cached,ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: databasename
    ports:
      - 3306:3306

  phpmyadmin:
    image: library/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: composer install --ignore-platform-reqs

  mailhog:
    image: mailhog/mailhog:latest
    hostname: mailhog
    ports:
      - 8025:8025
      - 1025:1025

  adminer:
    image: dockette/adminer:dg
    ports:
      - 8082:80
    restart: always

  vsftpd_server:
    image: wildscamp/vsftpd
    hostname: vsftpd
    restart: unless-stopped
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./.docker/ftp/data:/home/virtual/admin/home
    environment:
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30009
      VSFTPD_USER_1: 'admin:admin:1:'
